---
format:
  typst:
    include-before-body: 
      - file: 'training_header.typ'
    mainfont: 'Oswald'
    fig-format: svg
    fig-dpi: 600
params:
  training_date:
  data_path: 
knitr:
  opts_chunk:
    dev: svg
---

```{r setup, include=FALSE}

# Configured default plotting dimensions for landscape letter size
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggimage)
library(tinytable)

```

```{r}
load("stats_period.RData")
training_date <- as.Date("2026-05-27")


```

```{r, eval=F}
data_path <- params$data_path

stats_period <- readRDS(data_path)

md_input <- params$md_input

image1 <- params$image1

image2 <- params$image2

image3 <- params$image3

if (is.null(image1)) {
  image1 <- 'TidesFCImage5.jpg'
}
if (is.null(image2)) {
  image2 <- 'TidesFCImage6.jpg'
}
if (is.null(image3)) {
  image3 <- 'TidesFCImage7.jgp'
}

md_date <- stats_period %>% filter(activity_name==md_input) %>% mutate(date = paste0(weekdays(date), ', ', format(date, '%B %d, %Y'))) %>% pull(date) %>% unique
md_num <- str_extract(md_input, '(?<=MD\\s)\\d{1}')
md_year <- str_extract(md_date, '\\d{4}')

team_logo <- case_when(str_detect(md_input, "Montreal") ~ "Montreal.png",
                       str_detect(md_input, "Ottawa") ~ "Ottawa.png",
                       str_detect(md_input, "Toronto") ~ "Toronto.png",
                       str_detect(md_input, "Calgary") ~ "Calgary.png",
                       str_detect(md_input, "Vancouver") ~ "Vancouver.png",
                       str_detect(md_input, "Portsmouth") ~ "Portsmouth.png",
                       str_detect(md_input, "Everton") ~ "Everton.png",
                       str_detect(md_input, "West Ham") ~ "West Ham.png",
                       str_detect(md_input, "AUS") ~ "AUS.png")
```


```{=typst}

#show heading: set align(center)


#set table(inset: (x, y) => (
  x: 2pt,
  y: if y == 0 { 5pt } else { 3pt }
))


#let valuebox(title, value, color: rgb("0073e6")) = {
  block(
    fill: color.lighten(80%),
    stroke: 0.5pt + color,
    inset: 12pt,
    radius: 4pt,
    width: 100%,
    [
      #set text(fill: color.darken(20%), weight: "bold", size: 9pt)
      #upper(title)
      #v(-4pt)
      #set text(fill: rgb("#221C35"), size: 14pt, weight: "bold")
      #value
    ]
  )
}

```

```{r}
value_box_data <- stats_period %>%
  mutate(across(where(is.numeric), ~if_else(field_time == 0 & total_distance == 0, NA_real_, .x))) %>% 
  dplyr::filter(position_name != "Goal Keeper" & date == training_date) %>%
  group_by(athlete_name) %>%
  summarize(across(where(is.numeric) & !max_vel_kph, ~sum(.x, na.rm=T)), max_vel_kph=max(max_vel_kph,na.rm=T)) %>% 
  ungroup %>% 
  summarize(across(where(is.numeric), ~mean(.x, na.rm=T)))

total_distance <- value_box_data %>% pull(total_distance)

hsr_distance <- value_box_data %>% pull(high_speed_distance)

sprint_distance <- value_box_data %>% pull(sprint_distance)

accel_efforts <- value_box_data %>% pull(accel_efforts)

decel_efforts <- value_box_data %>% pull(decel_efforts)

max_vel <- value_box_data %>% pull(max_vel_kph)

```


---
# Dynamically pass the R variable to Quarto metadata
total_distance: '`r round(total_distance)`'
hsr_distance: '`r round(hsr_distance)`'
sprint_distance: '`r round(sprint_distance)`'
accel_efforts: '`r round(accel_efforts)`'
decel_efforts: '`r round(decel_efforts)`'
max_vel: '`r round(max_vel,1)`'
---

```{=typst}
#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 12pt,
  valuebox("Total Distance (m)", {{< meta total_distance >}}, color: rgb("#00B0B9")),
  valuebox("HSR Distance (m)",  {{< meta hsr_distance >}}, color: rgb("#572C5F")),
  valuebox("Sprint Distance (m)", {{< meta sprint_distance >}}, color: rgb("#00B0B9")),
  valuebox("Accel Efforts",  {{< meta accel_efforts >}}, color: rgb("#572C5F")),
  valuebox("Decel Efforts",  {{< meta decel_efforts >}}, color: rgb("#00B0B9")),
  valuebox("Max Velocity (km/h)",  {{< meta max_vel >}}, color: rgb("#572C5F"))

)

#v(12pt)
```

```{r}


player_daily_summary <- stats_period %>% 
      dplyr::filter(position_name != "Goal Keeper" & date == training_date) %>%
      select(position_name, athlete_name, period_name, total_distance, high_speed_distance, sprint_distance, accel_efforts, decel_efforts,meterage_per_minute,max_vel_kph, percentage_max_velocity, field_time) %>% 
      mutate(across(where(is.numeric), ~if_else(field_time == 0 & total_distance == 0, NA_real_, .x)),
             field_time=field_time/60,
             percentage_max_velocity=percentage_max_velocity/100
             ) %>% 
  group_by(athlete_name, position_name) %>% 
  summarize(across(where(is.numeric) & !max_vel_kph & !percentage_max_velocity, ~sum(.x,na.rm=T)), 
            across(max_vel_kph | percentage_max_velocity, ~ max(.x, na.rm=T))) %>% 
  ungroup %>% 
      rename(Position=position_name, Player = athlete_name, `Total Distance (m)` = total_distance, `HSR Distance (m)` = high_speed_distance, `Sprint Distance (m)` = sprint_distance, `Accel Efforts` = accel_efforts, `Decel Efforts`=decel_efforts, `Avg Speed (m/min)` = meterage_per_minute, `Max Speed (km/h)` = max_vel_kph, `Max Speed (%max)` = percentage_max_velocity) %>% 
  mutate(
    `Max Speed (%max)` = scales::percent(`Max Speed (%max)`, accuracy =0.1),
    across(where(is.numeric) & ! `Max Speed (km/h)`, round), 
    `Max Speed (km/h)`=round(`Max Speed (km/h)`,1)
  ) %>%
      drop_na(Position) %>% 
  select(!Position & !field_time)
    
    

names(player_daily_summary)[names(player_daily_summary) == "Total Distance (m)"] <- format_tt("Total Distance (m)", escape = "typst")
names(player_daily_summary)[names(player_daily_summary) == "HSR Distance (m)"] <- format_tt("HSR Distance (m)", escape = "typst")
names(player_daily_summary)[names(player_daily_summary) == "Sprint Distance (m)"] <- format_tt("Sprint Distance (m)", escape = "typst")
names(player_daily_summary)[names(player_daily_summary) == "Avg Speed (m\\/min)"] <- format_tt("Avg Speed (m\\/min)", escape = "typst")
names(player_daily_summary)[names(player_daily_summary) == "Max Speed (km\\/h)"] <- format_tt("Max Speed (km\\/h)", escape = "typst")
names(player_daily_summary)[names(player_daily_summary) == "Max Speed (%max)"] <- format_tt("Max Speed (%max)", escape = "typst")

# Custom function with dynamic color arguments
ggplot_progress_bar <- function(x, data_column, bar_fill = "#00B0B9", bar_outline = "#FFFFFF", text_color = "#FFFFFF", ...) {
  max_limit <- max(data_column, na.rm=T)
  percent_max <- x/max_limit
  df <- data.frame(val = x, per_max = percent_max, max_val = 1)
  
  p <- ggplot(df) +
    #Background bar
    geom_col(aes(x = max_val, y = 1), fill = "transparent", linewidth =1, color = bar_outline, width = 0.2) +
    #Foreground bar 
    geom_col(aes(x = per_max, y = 1), fill = bar_fill, linewidth =1,color = bar_outline, width = 0.2) +
    geom_text(aes(x = max_val/2, y = 1, label = val), color=text_color, hjust = "middle",fontface="bold", size = 16) +
    scale_x_continuous(expand = c(0.05, 0.05)) +
    scale_y_discrete(expand = c(0.01,0.01)) +
    theme_void()

}

player_daily_summary %>%
  tt(width=c(0.15,0.125,0.125,0.125,0.125,0.125,0.125,0.1,0.1)) %>% 
  theme_empty() %>% # Clear out the default black theme lines
  style_tt(i = 0, line = "tb", line_color = "#221C35", line_width = 0.05) %>%
  style_tt(i = nrow(player_daily_summary), line = "b", line_color = "#221C35", line_width = 0.05) %>% 
  format_tt(escape=T) %>% 
  # theme_tt("spacing", "compact")  %>%
  # style_tt(background = "#FFFFFF", color = "#221C35") %>% 
  style_tt(align = "lcccccccc", alignv = "m",line_color = "#221C35") %>% 
  style_tt(i = "colnames", bold = TRUE, alignv = "t") %>%
  plot_tt(j = 2, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`Total Distance (m)`), data_column=player_daily_summary$`Total Distance (m)`, bar_fill = rgb(0, 176, 185,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#00B0B9", text_color= "#221C35")  %>% 
  plot_tt(j = 3, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`HSR Distance (m)`), data_column=player_daily_summary$`HSR Distance (m)`, bar_fill =  rgb(87, 44, 95,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#572C5F", text_color= "#221C35") %>% 
  plot_tt(j = 5, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`Sprint Distance (m)`), data_column=player_daily_summary$`Sprint Distance (m)`, bar_fill = rgb(0, 176, 185,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#00B0B9", text_color= "#221C35") %>% 
  plot_tt(j =5, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`Accel Efforts`), data_column=player_daily_summary$`Accel Efforts`, bar_fill = rgb(87, 44, 95,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#572C5F", text_color= "#221C35") %>% 
  plot_tt(j = 6, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`Decel Efforts`), data_column=player_daily_summary$`Decel Efforts`, bar_fill = rgb(0, 176, 185,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#00B0B9", text_color= "#221C35") %>% 
    plot_tt(j =7, fun = ggplot_progress_bar,height=2, data = as.list(player_daily_summary$`Avg Speed (m/min)`), data_column=player_daily_summary$`Avg Speed (m/min)`, bar_fill = rgb(87, 44, 95,alpha=(0.2*255), maxColorValue = 255), bar_outline  = "#572C5F", text_color= "#221C35")
      
```

